# Generated by Django 5.1.4 on 2025-11-17 01:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tro_site", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày thêm"),
                ),
                (
                    "motel_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="tro_site.motelroom",
                        verbose_name="Phòng trọ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu thích",
                "verbose_name_plural": "Yêu thích",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="tro_site_fa_user_id_ef5125_idx",
                    )
                ],
                "unique_together": {("user", "motel_room")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Đánh giá (1-5 sao)",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Nhận xét")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày đánh giá"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "motel_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tro_site.motelroom",
                        verbose_name="Phòng trọ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người đánh giá",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá",
                "verbose_name_plural": "Đánh giá",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["motel_room", "-created_at"],
                        name="tro_site_re_motel_r_261743_idx",
                    )
                ],
                "unique_together": {("user", "motel_room")},
            },
        ),
    ]
